### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by TRECRF** [ljlVink/Squirrel-decoder#1]
Hi,is this a project about *** MDM on EMUI devices to change the package name of the apk for installing?

**Comment by ljlVink** [comment]
> Hi,is this a project about *** MDM on EMUI devices to change the package name of the apk for installing?

不是的，没有改包名

**Comment by TRECRF** [comment]
Uh... What's this Repositories about?

**Comment by TRECRF** [comment]
I have installed the evironment which is told by the README,but the program also tells the error about the mistaken dlls .So I copy some dlls from MinGW64 to the file folder.Then dec.exe tells“error 0xc000007b”.Maybe I installed the wrong version of  JDK?

**Comment by ljlVink** [comment]
额，这个还有点bug，等修

**Comment by ljlVink** [comment]
> Uh... What's this Repositories about?

1.过签名校验
2.魔改登录页面将它的一个登录处理去掉

**Comment by ljlVink** [comment]
> I have installed the evironment which is told by the README,but the program also tells the error about the mistaken dlls .So I copy some dlls from MinGW64 to the file folder.Then dec.exe tells“error 0xc000007b”.Maybe I installed the wrong version of JDK?

这个我没测试呢，代码我是用win 10 环境下g++ dec.cpp -o dec.exe编译的，您系统是win？
I didn't test this. I used the code in the win 10 environment with g++ dec.cpp -o dec.exe 
Is your system win7or win10?

**Comment by ljlVink** [comment]
> Uh... What's this Repositories about?

1.改签名校验
2.改登录界面的一个验证，这样就用fakeserver “登录”一次 然后下次再登录就会按照历史的班级号和名字去登录
这个服务器默认我是Android9的系统，但是我平板刷机成10了，没有9的包

**Comment by TRECRF** [comment]
> > I have installed the evironment which is told by the README,but the program also tells the error about the mistaken dlls .So I copy some dlls from MinGW64 to the file folder.Then dec.exe tells“error 0xc000007b”.Maybe I installed the wrong version of JDK?
> 
> 这个我没测试呢，代码我是用win 10 环境下g++ dec.cpp -o dec.exe编译的，您系统是win？
> I didn't test this. I used the code in the win 10 environment with g++ dec.cpp -o dec.exe
> Is your system win7or win10?

Windows10 Home 20H2 x64

**Comment by TRECRF** [comment]
> > I have installed the evironment which is told by the README,but the program also tells the error about the mistaken dlls .So I copy some dlls from MinGW64 to the file folder.Then dec.exe tells“error 0xc000007b”.Maybe I installed the wrong version of JDK?
> 
> 这个我没测试呢，代码我是用win 10 环境下g++ dec.cpp -o dec.exe编译的，您系统是win？
> I didn't test this. I used the code in the win 10 environment with g++ dec.cpp -o dec.exe
> Is your system win7or win10?

jdk我用的是最新版 环境配置全了 先是报错少一堆dll 我把DevCpp的安装目录的MinGW64的dll复制到了你程序目录下 之后dll报错没了 之后是报错0xc000007b

**Comment by TRECRF** [comment]
> 界面

原来如此 我是靠xposed+应用变量解决
mac校验其实是可选项 管理员能关 登记平板的时候应该记录sn了
